<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="WolverineFx.Marten" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PawMatch.BuildingBlocks.Domain\PawMatch.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

</Project>
