<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <NoWarn>CS1591</NoWarn>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Company>K9Crush</Company>
    <Product>K9Crush Platform</Product>
  </PropertyGroup>
</Project>
