<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Marten" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\ShelterAdoption\K9Crush.Modules.ShelterAdoption.Domain\K9Crush.Modules.ShelterAdoption.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\ShelterAdoption\K9Crush.Modules.ShelterAdoption.Api\K9Crush.Modules.ShelterAdoption.Api.csproj" />

    <ProjectReference Include="..\..\src\Modules\Profiles\K9Crush.Modules.Profiles.Domain\K9Crush.Modules.Profiles.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Profiles\K9Crush.Modules.Profiles.Api\K9Crush.Modules.Profiles.Api.csproj" />

    <ProjectReference Include="..\..\src\Modules\Identity\K9Crush.Modules.Identity.Domain\K9Crush.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\K9Crush.Modules.Identity.Api\K9Crush.Modules.Identity.Api.csproj" />

    <ProjectReference Include="..\..\src\Modules\Notifications\K9Crush.Modules.Notifications.Domain\K9Crush.Modules.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Notifications\K9Crush.Modules.Notifications.Api\K9Crush.Modules.Notifications.Api.csproj" />

    <ProjectReference Include="..\..\src\Modules\Admin\K9Crush.Modules.Admin.Domain\K9Crush.Modules.Admin.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Admin\K9Crush.Modules.Admin.Api\K9Crush.Modules.Admin.Api.csproj" />
  </ItemGroup>

</Project>
